# Generated by Django 3.1.2 on 2020-12-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201218_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='userName',
        ),
    ]
