# Generated by Django 3.1.2 on 2020-12-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20201220_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='defaultProfile.png', null=True, upload_to='static/images/'),
        ),
    ]
